### ISSUE TITLE
Update tests for `src/vessel-charging/BidParams.test.ts` using Jest

### ISSUE THREAD

**Issue by mariolo1985** [DAVFoundation/dav-js#83]
## first-timers-only

This issue is tagged 🕺  **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=first-timers-only+org%3ADAVFoundation+label%3A%22up-for-grabs%22&state=open&type=Issues).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### dav-js

This repo contains the DAV JavaScript SDK. This SDK allows developers to build applications and servers that connect to the DAV network. For example, allowing a drone to find charging stations, or an autonomous car to ask for traffic data.

## How you can help

In order to foster a community that is welcoming for open source contributions, it is important for us to have good test coverage. And good tests are simple, readable tests.

Here is a good opportunity to simplify one of our tests.

### The Issue

The `BidParams` class is instantiated at line [5](../blob/master/src/vessel-charging/BidParams.test.ts#L5) but it is missing the following arguments: 
  - amenities
  - provider
  - model
  - manufacturer

These arguments are being passed to and returned in our `serialize()` and `deserialize()` methods so the tests should include these arguments as well.

```javascript
  const bidParams = new BidParams({
    // parameters
  });
```

The [**serializedBidParams**](../blob/master/src/vessel-charging/BidParams.test.ts#L23) object is defined with the properties `amenities`, `provider`, `model` and `manufacturer` as value `undefined` 😅 and this is not meaningful.

```javascript
  const serializedBidParams: any = {
    amenities: undefined,
    provider: undefined,
    model: undefined,
    manufacturer: undefined,
    // other properties
  };
```

The tests should ensure `amenities`, `provider`, `model` and `manufacturer` are being passed through and returning correctly.

Please update this test by:

1. Importing the `Amenities` enum

```javascript
import { EnergySources, Amenities } from './enums';
```

2. Add arguments `amenities`, `provider`, `model` and `manufacturer` to the instantiation of `BidParams`

```javascript
import { EnergySources, Amenities } from './enums';

const bidParams = new BidParams({
  // existing params
  amenities: [Amenities.Docking, Amenities.Grocery],
  provider: 'Charging Co',
  model: 'iCharger',
  manufacturer: 'Vessel Chargers',
});
```

3. Update **serializedBidParams** object with the arguments (`amenities`, `provider`, `model` and `manufacturer`) passed above

```javascript
const serializedBidParams: any = {
  // existing properties
  amenities: [Amenities.Docking, Amenities.Grocery],
  provider: 'Charging Co',
  model: 'iCharger',
  manufacturer: 'Vessel Chargers',
};
```

After making your changes, run `npm run jest` to make sure our tests are passing.

### Contributing to dav-js

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment on this issue that you would like to do it (if you're the first you can start working on it immediately)
- [ ] Open [dav-js GitHub page](https://github.com/DAVFoundation/dav-js) and click the ★ Star and then ⑂ Fork buttons
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/dav-js.git`
- [ ] Install dependencies by running `npm install`
- [ ] Make sure everything is working and all tests pass by running `npm run jest`
- [ ] **Code Code Code**
- [ ] Make sure everything is still working and all tests pass by running `npm run jest` again
- [ ] Commit all your changes
- [ ] Push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/dav-js](https://github.com/YOUR-USER-NAME/dav-js)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#7`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by shalini-s** [comment]
Hey :) I'll take a shot at it!

**Comment by shalini-s** [comment]
I'm running into issues installing the dependencies with npm - not sure if this is a windows issue?
Getting these errors:
> dav-js@0.1.19 preinstall C\...\dav-js
> (rm .git/hooks/* && cp ./.githooks/* .git/hooks) || true
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dav-js@0.1.19 preinstall: `(rm .git/hooks/* && cp ./.githooks/* .git/hooks) || true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dav-js@0.1.19 preinstall script.

'rm' is not recognized as an internal or external command,
operable program or batch file.
'true' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mariolo1985** [comment]
Hey @shalini-s thanks for helping out! I am getting this error on Windodws as well. It is passing on a Mac :sweat_smile: I will let our devs know.

**Comment by mariolo1985** [comment]
Hi @shalini-s It looks like you found a bug 🐞 My apologize for the issue. We will let you know when this is resolved.

I have also added more depth to this issue. It is different from when you started. If you have any questions, you are more than welcome reach out 👐 .

**Comment by mariolo1985** [comment]
Hey @shalini-s, our devs pushed out a fix for Windows that should resolve the install errors. Could you pull from master and let me know if you are still getting install errors?

**Comment by shalini-s** [comment]
Hey, I pulled the updates but seem to be getting a bunch of different errors now:

gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\...\AppData\Local\Programs\Python\Python36-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:567:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\...\dav-js\node_modules\keccak
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2018-10-15T04_09_14_521Z-debug.log
"Keccak bindings compilation fail. Pure JS implementation will be used."

> scrypt@6.0.3 install C:\Users\...\dav-js\node_modules\scrypt
> node-gyp rebuild


C:\Users\...\dav-js\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\...\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\...\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\...\AppData\Local\Programs\Python\Python36-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:567:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\.\dav-js\node_modules\scrypt
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2018-10-15T04_09_17_740Z-debug.log

**Comment by TalAter** [comment]
@shalini-s Just before we dive into this, could you clone the latest version of the repository, do `npm install` again and let us know what you're getting?

**Comment by mariolo1985** [comment]
hi @shalini-s are you still interested in working on this?

**Comment by abdchehadeh** [comment]
@mariolo1985  @TalAter I will have a go with all the First timers. :)

**Comment by Fransan** [comment]
is this still an issue?
